### ISSUE TITLE
NPE when running with javaScriptBuildnumberCallback parameter under IDEA 2016.2 

### ISSUE THREAD

**Issue by mih-kopylov** [alx3apps/jgit-buildnumber#25]
Configuration:

```
        <plugin>
          <groupId>ru.concerteza.buildnumber</groupId>
          <artifactId>maven-jgit-buildnumber-plugin</artifactId>
          <version>1.2.10</version>
          <configuration>
            <javaScriptBuildnumberCallback>tag + branch</javaScriptBuildnumberCallback>
          </configuration>
          <executions>
            <execution>
              <phase>validate</phase>
              <goals>
                <goal>extract-buildnumber</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
```

When running `mvn package` all is great.
But when running `package` from IDEA 2016.2 getting NPE
![idea64_2016-07-25_10-43-03](https://cloud.githubusercontent.com/assets/6898003/17093886/9ecc42b4-5254-11e6-868a-7faa181af778.png)

```
[ERROR] 
java.lang.NullPointerException
    at ru.concerteza.util.buildnumber.JGitBuildNumberMojo.buildnumberFromJS(JGitBuildNumberMojo.java:198)
    at ru.concerteza.util.buildnumber.JGitBuildNumberMojo.createBuildnumber(JGitBuildNumberMojo.java:192)
    at ru.concerteza.util.buildnumber.JGitBuildNumberMojo.execute(JGitBuildNumberMojo.java:146)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
    at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:49)
```

Seems it's because `new ScriptEngineManager().getEngineByName("JavaScript")` returns `null`.

**Comment by mih-kopylov** [comment]
`new ScriptEngineManager()` searches engines implementations in current Thread's Classloader.
One should check if the engin isn't found and search without Classloader: `new ScriptEngineManager(null)`

**Comment by elab** [comment]
Merged into [my fork](https://github.com/elab/jgit-buildnumber) (which is also available on maven central).
Please let me know if you have any issues.
